"""nueva version de tablas usuarios

Revision ID: 19e8ad81b196
Revises: 4436e7e215d4
Create Date: 2025-03-17 18:10:14.346941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19e8ad81b196'
down_revision: Union[str, None] = '4436e7e215d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('password_hash', sa.String(length=255), nullable=False))
    op.add_column('usuarios', sa.Column('first_name', sa.String(length=100), nullable=False))
    op.add_column('usuarios', sa.Column('last_name', sa.String(length=100), nullable=False))
    op.add_column('usuarios', sa.Column('date_of_birth', sa.DateTime(), nullable=False))
    op.add_column('usuarios', sa.Column('phone_number', sa.String(length=20), nullable=True))
    op.add_column('usuarios', sa.Column('shipping_address', sa.String(length=255), nullable=True))
    op.add_column('usuarios', sa.Column('shipping_city', sa.String(length=100), nullable=True))
    op.add_column('usuarios', sa.Column('shipping_country', sa.String(length=100), nullable=True))
    op.add_column('usuarios', sa.Column('shipping_zip_code', sa.String(length=10), nullable=True))
    op.add_column('usuarios', sa.Column('account_status', sa.Enum('active', 'pending', 'banned', 'deleted', name='accountstatus'), nullable=True))
    op.add_column('usuarios', sa.Column('role', sa.String(length=20), nullable=True))
    op.add_column('usuarios', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('usuarios', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('usuarios', sa.Column('last_login', sa.DateTime(), nullable=True))
    op.add_column('usuarios', sa.Column('two_factor_enabled', sa.Boolean(), nullable=True))
    op.add_column('usuarios', sa.Column('is_email_verified', sa.Boolean(), nullable=True))
    op.add_column('usuarios', sa.Column('email_verification_token', sa.String(length=100), nullable=True))
    op.add_column('usuarios', sa.Column('email_verification_expiration', sa.DateTime(), nullable=True))
    op.drop_index('ix_usuarios_email', table_name='usuarios')
    op.drop_index('ix_usuarios_id', table_name='usuarios')
    op.create_unique_constraint(None, 'usuarios', ['email'])
    op.drop_column('usuarios', 'es_admin')
    op.drop_column('usuarios', 'nombre')
    op.drop_column('usuarios', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('usuarios', sa.Column('nombre', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('usuarios', sa.Column('es_admin', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'usuarios', type_='unique')
    op.create_index('ix_usuarios_id', 'usuarios', ['id'], unique=False)
    op.create_index('ix_usuarios_email', 'usuarios', ['email'], unique=True)
    op.drop_column('usuarios', 'email_verification_expiration')
    op.drop_column('usuarios', 'email_verification_token')
    op.drop_column('usuarios', 'is_email_verified')
    op.drop_column('usuarios', 'two_factor_enabled')
    op.drop_column('usuarios', 'last_login')
    op.drop_column('usuarios', 'updated_at')
    op.drop_column('usuarios', 'created_at')
    op.drop_column('usuarios', 'role')
    op.drop_column('usuarios', 'account_status')
    op.drop_column('usuarios', 'shipping_zip_code')
    op.drop_column('usuarios', 'shipping_country')
    op.drop_column('usuarios', 'shipping_city')
    op.drop_column('usuarios', 'shipping_address')
    op.drop_column('usuarios', 'phone_number')
    op.drop_column('usuarios', 'date_of_birth')
    op.drop_column('usuarios', 'last_name')
    op.drop_column('usuarios', 'first_name')
    op.drop_column('usuarios', 'password_hash')
    # ### end Alembic commands ###
